# Generated by Django 2.1.4 on 2018-12-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, verbose_name='语言')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('company', models.CharField(max_length=30, verbose_name='公司')),
                ('scale', models.CharField(max_length=15, verbose_name='规模')),
                ('xueli', models.CharField(max_length=10, verbose_name='学历')),
                ('lat', models.FloatField(max_length=15, verbose_name='纬度')),
                ('longitude', models.FloatField(max_length=15, verbose_name='经度')),
                ('post', models.CharField(max_length=20, verbose_name='职位')),
                ('salary', models.CharField(max_length=10, verbose_name='薪资')),
                ('salary_min', models.IntegerField(default=0, verbose_name='最少薪资')),
                ('exp', models.CharField(max_length=10, verbose_name='工作经验')),
                ('exp_min', models.IntegerField(default=0, verbose_name='最低工作经验')),
                ('welfare', models.CharField(max_length=30, verbose_name='福利')),
            ],
        ),
    ]
